services:
  postgres-db:
    image: postgres:15
    environment:
      # O Docker puxa os valores do arquivo .env automaticamente
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"