# Conexão com o Banco de Dados usando Variáveis de Ambiente
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Pede pro Spring criar/atualizar as tabelas no banco automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
